### ISSUE TITLE
Install Azure ML Extension runtime dependencies does not complete [Windows]

### ISSUE THREAD

**Issue by spdjudd** [microsoft/vscode-tools-for-ai#126]
Similar to #120, but on Windows 10.  I'm using the 0.4.1 release, verified I have azureml sdk 1.0.2 installed, and tried deleting the .azureml directory.  I've tried uninstalling the extension and reinstalling, but the runtime dependencies install step still fails with:

`verbose: Flask Stdout: 
warn: Starting local flask server timed out.
warn: Azure ML extension flask server couldn't be initialized: Error: Timeout of 500ms exceeded`

Are there any logs I can check or generate, or any other troubleshooting?

**Comment by LittleLittleCloud** [comment]
Usually, such error means the azureml dependency doesn't install correctly.  Could you provide the following information so we may reproduce the error

1. how do you install azureml sdk, is that through pip?
2. which verison of python do you use
3. do you use conda or any other environment management tools?

And if may, could you provide the detailed steps of causing that error? here's an example
1. uninstall aml extension
2. remove .azureml
3. install aml extension
4. run "install azure ml sdk" command
5. launch and error

**Comment by greazer** [comment]
We have had reports of this problem from other users as well and are actively investigating. 

What we currently know is that it can be worked around by deleting your ~/.azureml directory (this is the one that gets setup by the extension) and then just running an Azure ML scenario in the extension again. The extension will detect that it's runtime dependencies (the Azure ML SDK that gets installed to ~/.azureml) need to be updated and will re-install it. 

After that the extension should work. 

Please note that the version of the Azure ML extension that is used by the extension is specifically NOT the same one you may install for your own project's use. We want to make sure that the extension is always using a version it's been tested with.

**Comment by shsuman** [comment]
Well, the extension is supposed to work on its own so you do not have to install the sdk. It installs the sdk in its own environment whenever you install the extension and click on the Azure Tab in VS Code(basically when the extension loads). If you would, can you please try the following on your broke machine so that i could investigate more.

1) Uninstall the Azure: Machine Learning extension. Delete .azureml folder
2) Select a different Python interpreter in VS Code
3) Install the extension and click on the Azure Tab.
4) Also make sure you have Python extension installed. 

Also can you try to install the SDK verison 1.0.2 through the Python you were using in the first place by running the following line on cmd

C:\Users\<user>\AppData\Local\Continuum\anaconda3\python -m pip install azureml-sdk==1.0.2 and see the results.

**Comment by spdjudd** [comment]
@shsuman I tried your steps - selecting a different python interpreter makes no difference, ~\.azureml\envs\amlsdk\Lib\site-packages is still empty after reinstalling the extension and installing dependencies.

I uninstalled the SDK, then reinstalled as per your command - that worked ok.  There was a warning about the version of ruamel.yaml:

`azureml-core 1.0.2 has requirement ruamel.yaml<=0.15.51,>=0.15.35, but you'll have ruamel-yaml 0.11.14 which is incompatible`

I tried explicitly updating ruamel.yaml in my base conda environment, then re-running the extension uninstall/reinstall with that interpreter seleced in vscode - still no joy, the site-packages is still empty.

**Comment by shsuman** [comment]
Hey @spdjudd, Thanks for doing that. I still can't understand what is the problem. Can you help me a little more here to understand the problem. So, What I would like you to do is 
: 1) Take this piece of code below and save it in a notepad file with extension .bat, so juts copy in a new text document and save as Test.bat. 

setlocal
set AML_HOME=%HOMEDRIVE%%HOMEPATH%\.azureml

set PYTHONBIN=C:\Users\shsuman\AppData\Local\Programs\Python\Python36-32\python.exe
set AML_VERSION=0.1.8

call "%PYTHONBIN%" -m venv "%AML_HOME%\envs\amlsdk"
call "%AML_HOME%\envs\amlsdk\scripts\activate.bat"

python -m pip install --upgrade pip
python -m pip install flask
python -m pip install azureml-sdk==%AML_VERSION%
call "%AML_HOME%\envs\amlsdk\scripts\deactivate.bat"

2) Now run this file. it will prompt you to enter the python path. Type your python path and hit enter and then see the results.

Also open VS Code, click on Settings in the bottom left and then click settings and search for Python: Python Path under Workspace settings. Is it the same python that you want to  use ??

**Comment by surefire-gregf** [comment]
I'm also having the same issue and was unable to get it working using the provided workaround.

I also just crated a new VM in Azure, with a fresh install of Anaconda 3.7 and VS Code.  Installed the python extension and could execute python code no problem.  I then installed the Azure ML extension and received the same error as my local machine.

**Comment by spdjudd** [comment]
Thanks @shsuman - with that I have found the issue and fixed it.  The `venv create` step was failing (`Error: Command '['C:\\Users\\xxx\\.azureml\\envs\\amlsdk\\Scripts\\python.exe', '-Im', 'ensurepip', '--upgrade', '--default-pip']' returned non-zero exit status 1.`)  This was leaving the incomplete azureml venv, missing `activate.bat` and pip etc. 

Looking at [this SO issue](https://stackoverflow.com/questions/26215790/venv-doesnt-create-activate-script-python3), updating my anaconda python version fully fixed the issue: `conda update python`

(This upgraded python to 3.6.3 -> 3.6.8, but reverting to 3.6.3 again still worked, so obviously not a general problem with that python version, but something I'd managed to break.)

Anyway, thanks for the help - in the end not an issue with the extension, but I guess ideally the install would produce some diagnostics to make it easier to see what's happening?

**Comment by surefire-gregf** [comment]
Running that batch file the only error output I get is the following:  azure-cli-core 2.0.54 has requirement azure-mgmt-resource==2.0.0, but you'll have azure-mgmt-resource 2.1.0 which is incompatible.

When the extension starts up, I still receive the two below errors.
The request did not have a provided subscription. All requests must have an associated subscription Id.
Internal extension error: Azure ML extension flask server couldn't be initialized: Error: Timeout of 500ms exceeded.

I am signed into my Azure account and can see my experiment.  I also tried using a different Azure account/subscription.  Windows Firewall is also off.

**Comment by shsuman** [comment]
@surefire-gregf As for your issue, Python 3.7 is not completely supported right now. Please use Python 3.6 and see if the problem persists.

**Comment by surefire-gregf** [comment]
Thanks @shsuman using version 3.6.5 that resolved the issue.

**Comment by surefire-gregf** [comment]
I'm still having difficulties.  When I run an experiment locally, I receive an error in the logs stating "AZ CLI" not installed.  I installed both the Azure CLI and the Azure CLI ML package.  Next, I installed the pip packages azure-cli and azure-cli-ml, but my experiment will still not run.  The logs now state "Exception thrown while executing CLI command"  Also, when installing the azure-cli I received an error (attempting to install msrestazure 0.4.11 causes all sorts of errors):

azure-mgmt-recoveryservices 0.1.0 has requirement msrestazure~=0.4.11, but you'll have msrestazure 0.6.0 which is incompatible.
azure-mgmt-recoveryservicesbackup 0.1.1 has requirement msrestazure~=0.4.11, but you'll have msrestazure 0.6.0 which is incompatible.
azure-mgmt-datalake-analytics 0.2.0 has requirement msrestazure~=0.4.7, but you'll have msrestazure 0.6.0 which is incompatible.

**Comment by shsuman** [comment]
are you trying to use azure datalake analytics compute ?

**Comment by surefire-gregf** [comment]
I am not.  First I tried the regression tutorial: https://docs.microsoft.com/en-us/azure/machine-learning/service/tutorial-auto-train-models, then the classification tutorial, then finally my own ML script.  They all fail when trying to run the experiment with the same errors as above.  I just deleted the .azureml folder, reinstalled the extension and sdk, etc. and got the same issue.

**Comment by shsuman** [comment]
and you are running all this on your local machine and not on a Azure compute ?

**Comment by shsuman** [comment]
@greazer can you take a look at this ?

**Comment by duanekord** [comment]
@shsuman Thank You- I searched high and low and this was the only thing that worked for me.

Uninstall the Azure: Machine Learning extension. Delete .azureml folder
Select a different Python interpreter in VS Code ( I was using 3.7.3 and it didn't work.  Switched to 3.6.8 and it worked)
Install the extension and click on the Azure Tab.
Also make sure you have Python extension installed.

**Comment by avivhu** [comment]
Confirming @duanekord solution: I had a flask error with in Python 3.7.3, I successfully to installed the Azure ML Extension with Python 3.6.8. 
I think this bug should be reopened. @greazer

**Comment by LavMehta** [comment]
Python 3.6.8 
Installed Azure ML extension, still it shows : No python interpreter selected. Please select a python interpreter in VS code. 
Dependencies are already installed. and it takes just fraction of seconds to install Azure ML extension. 
Also tried installing Azure ML SDK through pip but no good news.

**Comment by shsuman** [comment]
@LavMehta Do you have Python Extension installed ? If yes, then please try to select interpreter using the 'Select Python Interpreter' button in the status bar or using Command Palette 'Python: Select Interpreter'. Please ensure that you have correct Python version selected.

**Comment by greazer** [comment]
Also @LavMehta, it may be you're running into issue #25, but should have been fixed in release 0.5.0. So this may not be the same problem. Which version of the extension are you running?

**Comment by LavMehta** [comment]
@shsuman Yes i have python version 3.6.8 as well  as 3.7.1 but as per above mentioned discussion after installing the extension i am selecting 3.6.8 version as python interpreter. 
@greazer Hi jim, i am using extension version 0.5.0 but unfortunaetly still facing this problem.

**Comment by shsuman** [comment]
@LavMehta can you please follow these steps ? 
1) Uninstall the extension from VSCode. 
2) Delete the .azureml folder as wells as .vscode/extensions/ms-toolsai.vscode-ai-* in C:\Users\<user> folder (~/Users/<user> in Mac & .~/home/<user> in Ubuntu 
3) Now Reinstall the extension, see if the problem persists. If it does, please Go in Settings in VSCode in the left bottom corner, search for Python: Python Path, in user settings, set your desired python path here and try again.

Also, can you please tell us which OS and VSCode version are you using ?

**Comment by LavMehta** [comment]
@shsuman 
After following all the steps i am getting following errors: 
![ErroML](https://user-images.githubusercontent.com/45895526/56967775-331cc000-6b62-11e9-9d4d-0610e661d712.jpg)
![waiting](https://user-images.githubusercontent.com/45895526/56967792-39ab3780-6b62-11e9-9401-de35df09eac9.jpg)

**Comment by shsuman** [comment]
@LavMehta  Thank you for doing this. I think there's some problem with the dependencies installation. Can you please try to run the following script on your machine.

setlocal
set AML_HOME=%HOMEDRIVE%%HOMEPATH%.azureml

set PYTHONBIN=Type your own python path here
set AML_VERSION=1.0.15

call "%PYTHONBIN%" -m venv "%AML_HOME%\envs\amlsdk"
call "%AML_HOME%\envs\amlsdk\scripts\activate.bat"

python -m pip install --upgrade pip
python -m pip install flask
python -m pip install azureml-sdk==%AML_VERSION%
call "%AML_HOME%\envs\amlsdk\scripts\deactivate.bat"

Remember to enter your python path in line 4. Running this script should give us the actual errors on command line. If you get the access denied while running it, please try to run it as administrator. Feel free to reach out to me directly at shsuman@microsoft.com if you face any problem running it.

**Comment by shsuman** [comment]
@LavMehta Its probably a problem with your ensurePip or venv module. Before you do all of the steps mentioned above,, please try this on your command line:

python3 -m venv "xyz"
and see if it works
